### ISSUE TITLE
Please consider changing the module name

### ISSUE THREAD

**Issue by jberger** [pplu/mojo-ioloop-future#1]
If Mojolicious was ever going to implement native Futures this would certainly be the namespace we would want. It would be very kind of you to allow that possibility.

I propose alternatively to name it something under the Future namespace. I doubt that calling it Future::MojoIOLoop would prevent any features in Future from being implemented there.

**Comment by jberger** [comment]
Note that you would have to release the PAUSE permissions too.

**Comment by pplu** [comment]
Hi,

I was following the naming from the other modules that adapt Future to the event loop, like:

AnyEvent::Future
IO::Async::Future
POE::Future

Do you think it's permissible for me to use the Mojo::IOLoop::Future namespace for consistency? Wouldn't Mojo implement Futures in Mojo::Future, instead of in the IOLoop namespace? Any suggestions?

**Comment by nicomen** [comment]
Wouldn't MojoX::IOLoop::Future make sense?

**Comment by pplu** [comment]
Looks good. Sold!

**Comment by pplu** [comment]
Done. Uploaded MojoX::IOLoop::Future, deleted Mojo::IOLoop::Future versions from CPAN, and gave up maintainership on it.

**Comment by jberger** [comment]
we thank you for your understanding, :+1:

On Wed, Mar 4, 2015 at 2:39 PM, Jose Luis Martinez <notifications@github.com
